---
title: "DATA605 WK5 Assignment 5"
author: "Javern Wilson"
date: "9/28/2019"
output: html_document
---

```{r include=FALSE}
library(tidyverse)
```


## Choose independently two numbers B and C at random from the interval [0, 1] with uniform density. Prove that B and C are proper probability distributions.   Note that the point (B,C) is then chosen at random in the unit square. 


```{r}
set.seed(123)
B <- runif(10000, 0, 1)
C <- runif(10000, 0, 1)
```

## Find the probability that: 

### (a) $B + C < 1/2$

```{r}
X <- B + C
sum(X < 1/2)/10000
```


### (b) $BC < 1/2$

```{r}
X <- B * C
sum(X < 1/2)/10000

```



### (c) $|B − C| < 1/2$

```{r}
X <- abs(B - C)
sum(X < 1/2)/10000

```



### (d) $max\{B,C\} < 1/2$


```{r}
sum(pmax(B, C) < 1/2) / 10000

```



### (e) $min\{B,C\} < 1/2$

```{r}
sum(pmin(B, C) < 1/2) / 10000

```


#### Helpful links:

+ [Generating random numbers](http://www.cookbook-r.com/Numbers/Generating_random_numbers/)
+ [Maxima and Minima](http://www.endmemo.com/program/R/pmin.php)