---
title: "DATA605 Assignment 15"
author: "Javern Wilson"
date: "11/25/2019"
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    theme: cosmo
---

## Question 1

Find the equation of the regression line for the given points.  Round any final values to the nearest hundredth, if necessary.

*(5.6, 8.8), (6.3, 12.4), (7, 14.8), (7.7, 18.2), (8.4, 20.8)*

```{r}
x <- c(5.6, 6.3, 7, 7.7, 8.4 )
y <- c(8.8, 12.4, 14.8, 18.2, 20.8)
df <- data.frame(cbind(x, y))

xy.lm <- lm(y ~ x, data = df)
xy.lm

plot(df$x, df$y)
abline(xy.lm, col="blue")

```

The equation of the line is:

$$y = -14.8 + 4.257 \times x$$

## Question 2

Find all local maxima, local minima, and saddle points for the function given below.  Write your answer(s) in the form (x, y, z). Separate multiple points with a comma. 

$f (x, y) = 24x -  6xy^2 - 8y^3$

\[
f_x(x,y) = 24-6y^2\\
f_y(x,y) = -12xy - 24y^2
\]


\begin{aligned}
24 - 6y^2 = 0\\
4(4-y^2) = 0\\
y^2 = 4\\
y = \pm 2\\\\\\

-12x(-2 )- 24(-2)^2 = 0\\
24x - 96 = 0\\
x = 4\\\\

-12x(2) - 24(2)^2 = 0\\
-24x - 96 = 0\\
x = -4
\end{aligned} 


Therefore the critical points are **(4, -2)** and **(-4, 2)**

We must then use the Second Derivave Test to obtain whether equation has local minima, maxima and saddle points.




$$f_{_{xx}}(x,y) = 0\\
f_{_{yy}}(x,y) = -12x - 48y\\
f_{_{xy}}(x,y) = -12y\\\\$$

$$D = f_{_{xx}}(x,y).f_{_{yy}}(x,y)-[f_{_{xy}}(x,y)]^2\\
= 0 (-12x - 48y) - (12y)^2\\
=-144y^2\\\\\\$$

$$D(4,-2) = -576 < 0  \therefore (4,-2) \ is \ a \ saddle \ point\\
D(-4,2) = -576 < 0  \therefore (-4,2) \ is \ a \  saddle \ point$$




## Question 3


A grocery store sells two brands of a product, the "house" brand and a "name" brand.  The manager estimates that if she sells the "house" brand for x dollars and the "name" brand for y dollars, she will be able to sell 81 - 21x + 17y units of the "house" brand and 40 + 11x - 23y units of the "name" brand.
3. 

**Step 1. Find the revenue function R (x, y).**

To find pending revenue we multiply the amount of units to sell times the dollar amount.

Therefore the revenue function is like so:

$x(81 - 21x + 17y) + y(40 + 11x -23y)$

Simplfied we get:

$-21x^2 -23y^2 + 28xy + 81x + 40 y$


**Step 2. What is the revenue if she sells the "house" brand for \$2.30 and the "name" brand for \$4.10?**

$$-21(2.30)^2 -23(4.10)^2 + 28(2.30)(4.10) + 81(2.30) + 40(4.10)\\
-111.09 - 386.63 + 264.04 + 186.3 + 164\\
=116.62$$


## Question 4


A company has a plant in Los Angeles and a plant in Denver.  The firm is committed to produce a total of 96 units of a product each week.  The total weekly cost is given by $C(x, y) = \frac{1}{6}x^2 + \frac{1}{6}y^2 + 7x + 25y + 700$,  where x is the number of units produced in Los Angeles and y is the number of units produced in Denver.  How many units should be produced in each plant to minimize the total weekly cost?



$$f_x(x,y) = \frac{1}{3}x + 7\\
\frac{1}{3}x + 7 =0\\
x = -21\\$$

$$f_y(x,y) = \frac{1}{3}y + 25\\
\frac{1}{3}y + 25 = 0\\
y = -75$$


Using the absolute values of `x` and `y`, the amount of units for minimum cost weekly is `21` and `75` respectively.

## Question 5


Evaluate the double integral on the given region. 

$$ \iint_R (e^{8x + 3y})dA ; R:2 \le x \le 4 \ and \ 2 \le y \le 4$$


Write your answer in exact form without decimals.



$$\iint_R (e^{8x + 3y})dA=\int_2^4 \int_2^4 e^{8x + 3y} \\
= \int_2^4 \bigg[\frac{1}{8} e^{8x + 3y}\bigg]_2^4\\
= \int_2^4  \frac{1}{8} \bigg( e^{32 + 3y}- e^{16 + 3y}\bigg)\\
= \frac{1}{8} \int_2^4 e^{16}- 1 \bigg(e^{16 + 3y}\bigg)\\
= \frac{1}{8} \bigg(e^{16} - 1 \bigg) \int_2^4 e^{16 + 3y}\\
= \frac{1}{8} \bigg(e^{16} - 1 \bigg).\frac{1}{3} \bigg[ e^{16 + 3y}\bigg]_2^4\\
= \frac{1}{24} e^{16} - 1 \bigg(e^{16 + 12} - e^{16 + 6}\bigg)\\
= \frac{1}{24} e^{16} - 1 \bigg(e^{28} - e^{22}\bigg)\\
= \frac{1}{24} \bigg(e^{44} - e^{38} - e^{28} + e^{22}\bigg)$$


